{% set name = "dsgp4" %}
{% set org = "esa" %}
{% set version = "1.1.4" %}
{% set sha256 = "9d1468005686da47f5a317e7c987a765618c76d09cc89baa779149702a3308f1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools
    - pytorch
    - matplotlib-base

test:
  imports:
    - dsgp4
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/esa/dSGP4/
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: 'dSGP4 is a differentiable SGP4 program, which also supports ML-enhanced orbital propagation.'
  description: |
    *dsgp4* is a differentiable SGP4 program. It is written using PyTorch, which
    enables automatic differentiation through SGP4 inputs and parameters, as well as 
    batch propagation (across different TLEs), with the possibility of leveraging 
    embarassingly parallel computations both on CPU and GPU. It also offers the possibility
    of enabling a machine learning module that can enhance SGP4 propagation learning from high-precision
    simulated or observed orbital data. It  also features a TLE module for easily parsing, 
    interfacing with and constructing Two-Line Elements data. 
  doc_url: https://esa.github.io/dSGP4/
  dev_url: https://github.com/esa/dSGP4/

extra:
  recipe-maintainers:
    - Sceki
